name: Test import custom action

on: [push]

jobs:
  build-docs:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Run custom action
        id: build_docs
        uses: silva-vinicius/mkdocs-build-action@composite-action
        with:
          python-version: 3.8
      - name: show GITHUB_OUTPUT
        run: echo ${{ steps.build_docs.outputs.built_dir }}
      - name: save artifact
        uses: actions/upload-artifact@v3
        with:
          name: built_dir
          path: ${{ steps.build_docs.outputs.built_dir }}