name: Test import custom action

on: [push]

jobs:
  build-docs:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Run custom action
        id: build-docs
        uses: silva-vinicius/mkdocs-build-action@composite-action
        with:
          python-version: 3.9
      - name: show GITHUB_OUTPUT
        run: echo $GITHUB_OUTPUT
      - name: save artifact
        uses: actions/upload-artifact@v3
        with:
          name: built-dir
          path: ${{ steps.build-docs.outputs.built_dir }}